

services:
  #  db:
  #     image: mongod
  #     container_name: 
  #     restart: always
  #     ports:
  #     - 
  #     environment:

  #     volumes:
  #     networks:
  rabbitmq:
      image: rabbitmq:3-management
      container_name: rabbitmq
      ports:
       - "5672:5672"
       - "15672:15672"
      environment:
        RABBITMQ_DEFAULT_USER: guest
        RABBITMQ_DEFAULT_PASS: guest


volumes:
  mongodb:
networks:
  taskify-network:
    driver: bridge